version: '3.7'

volumes:
  postgres_data: {}

services:
  web:
    build: .
    restart: always
    container_name: frenglish_django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: frenglish_database
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "7000:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: "frenglish"
      POSTGRES_PASSWORD: "UNSAFEDBPASSWD"
      POSTGRES_DB: "frenglish_data"
